name: CI on Push and Pull Request

on: [push, pull_request]

jobs:        
  Android:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android
      run: | 
        nuget restore
        cd RCPad/RCPad.Android
        msbuild RCPad.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release 
    - uses: actions/upload-artifact@v2
      with:
        name: Android App
        path: RCPad/RCPad.Android/bin/Release/com.companyname.rcpad-Signed.apk
        
  iOS_Simulator:

    runs-on: macos-latest
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: iOS Simulator
      run: | 
        nuget restore
        msbuild RCPad.iOS/RCPad.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Release
        
    - uses: actions/upload-artifact@v2
      with:
        name: iOS Simulator App
        path: RCPad/RCPad.iOS/bin/iPhoneSimulator/Release/rcpad.iOS.app
         