name: NuGet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pack-push: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.401

    - name: Geração do package
      run: dotnet pack Pad/Pad.csproj -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
